package com.example.mountain

class Trail(
    val id: Int,
    val name: String,
    val description: String,
    val points: Array<String>,
    val thumbnail: String,
    var isRunning: Boolean = false,
    var seconds: Int = 0,
    var minutes: Int = 0,
    var hours: Int = 0,
    var savedSeconds: Int=0,
    var savedMinutes: Int=0,
    var savedHours: Int=0
) {
    companion object {
        val trails = arrayOf(
            Trail(0, "Czupel", "Najwyższy szczyt Beskidu Małego - ma 933 metry n.p.m. Zaliczany jest jednocześnie do Korony Gór Polski (28 najwyższych szczytów pasm górskich Polski) i do Małej Korony Beskidów (15 szczytów Beskidu Śląskiego, Żywieckiego i Małego).", arrayOf("Przełęcz Przegibek", " Schronisko PTTK Na Magurce", "Czupel"), thumbnail = "https://ocdn.eu/pulscms-transforms/1/m2Gk9kpTURBXy80MTI0NDcyYjM4YjA2NzQ4ZTJkZmZkMjRlZDFkMTQxZS5qcGeTlQMAHM0DhM0B-pUCzQSwAMPDkwmmM2I3ZjQyBt4AAaEwAQ/beskid-slaski.jpeg"),
            Trail(1, "Babia Góra", "Najwyższy szczyt Beskidu Żywieckiego i całego zachodniego Beskidu Śląskiego, oraz trzeci co do wysokości szczyt Polski (po Rysach i Czarnym Groniu).", arrayOf("Przełęcz Krowiarki", "Schodnie Koniarki", "Babia Góra"), thumbnail = "https://portaltatrzanski.pl/upload/article/fcf58149b97ee41d499c32a77e7c5cb0.jpeg"),
            Trail(2, "Giewont", "Jedna z najbardziej charakterystycznych gór Polski. Jej zachodnie stoki opadają stromo ku Zakopanemu, tworząc charakterystyczny, 1-kilometrowej długości garb w formie graniowego cypla zwieńczonego trzema turniami, położonymi jedna za drugą.", arrayOf("Polana Strążyska", "Przełęcz Bystra Ławka", "Giewont"), thumbnail = "https://portaltatrzanski.pl/upload/article/5baf7382a3d07b2a8c2c7f3c2b9218f2.jpeg"),
            Trail(3, "Kasprowy Wierch", "Drugoroczna kolejka górska w Polsce, czynna od grudnia do kwietnia. Z dworca na Kasprowy Wierch rozciąga się szeroki widok na Tatry.", arrayOf("Dolina Kasprowa", "Przełęcz Kondracka", "Kasprowy Wierch"), thumbnail = "https://portaltatrzanski.pl/upload/article/669287da5a7bdefdee4a7571e2b3f136.jpeg"),
            Trail(4, "Rusinowa Polana", "Kaplica Matki Bożej Jaworzyńskiej na Wiktorówkach znana też jako Kaplica Matki Bożej Królowej Tatr lub Sanktuarium Matki Bożej Jaworzyńskiej Królowej Tatr to miejsce chętnie odwiedzane przez turystów. Położona w gęstym świerkowym lesie sprzyja zadumie i kontemplacji.", arrayOf("Wierchoporoniec", "Rusinowa Polana"), thumbnail = "https://hasajacezajace.com/wp-content/uploads/2021/01/rusinowa-polana-39.jpg"),
            Trail(5, "Chybotek", "Najwyżej położony siedmiokątny kamień o wadze kilkudziesięciu ton i średnicy około czterech metrów wsparty jest jedynie w dwóch miejscach. Daje się on rozkołysać i stąd nazwa – „Chybotek”. Obok są inne mniejsze skałki, podobnie poukładane. Związane są z nimi walońskie legendy o Duchu Gór. Jedna z nich podaje, że skała zamykała wejście do podziemnego skarbca, a otaczała ją aura tajemniczości.", arrayOf("Szklarska Poręba", "Chybotek"), thumbnail = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1304_Chybotek_Szklarska_Por%C4%99ba_DJE_2.jpg/1200px-1304_Chybotek_Szklarska_Por%C4%99ba_DJE_2.jpg"),
            Trail(6, "Połonina Wetlińska", "Połonina Wetlińska wraz ze słynną Chatką Puchatka na grani to bez wątpienia jeden z najpiękniejszych fragmentów Bieszczadzkiego Parku Narodowego.", arrayOf("Przełęcz Wyżna", "Brzegi Górne", "Chatka Puchatka", "Przełęcz Orłowicza", "Wetlina"), thumbnail = "https://www.info.bieszczady.pl/wp-content/uploads/2023/08/14-1.jpg"),
            Trail(7, "Sokolica", "Sokolica jest jednym najbardziej rozpoznawalnych pienińskich szczytów a do tego miejscem z którego roztacza się przepyszna panorama. I to zarazem wertykalnej jak i w horyzontalnej perspektywie. Widok okraszony jest obecnością słynnej sosenki, która pomimo przeciwności losu, wciąż trwa i przyciąga kolejne rzesze turystów.", arrayOf("Krościenko", "Sokolica"), thumbnail = "https://gorskim-szlakiem.pl/wp-content/uploads/2021/12/P1000533-e1638879467786-1024x640.jpg"),
            Trail(8, "Śnieżka", "Śnieżka znacznie góruje nad otaczającymi ją grzbietami. Wznosi się w zachodniej części Czarnego Grzbietu.", arrayOf("Karpacz", "Samotnica", "Strzecha Akademicka", "Snieżka"), thumbnail = "https://i.wpimg.pl/1200x/filerepo.grupawp.pl/api/v1/display/embed/56567d5f-1879-4c99-9249-5a4727332138"),
            Trail(9, "Łysica", "Łysica zbudowana jest z kwarcytów i łupków kambryjskich. Od strony północnej i południowej szczyt otaczają gołoborza. Łysica jest całkowicie porośnięta lasem. W partiach szczytowych rośnie jodła, a poniżej las jodłowo-bukowy. Na stoku południowym, na wysokości ok. 590 m, położone jest niewielkie torfowisko.", arrayOf("Święta Katarzyna", "Puszcza Jodłowa", "Łysica"), thumbnail = "https://marcinkarpinski.pl/img/relacja/kgp-lysica/1200-kgp-lysica-023.webp"),
            Trail(10, "Dolina Kościeliska", "Dolina Kościeliska ma licznych wielbicieli. Bywa uważana za jedną z najpiękniejszych tatrzańskich dolin, bogatą w atrakcje przyrodnicze oraz pamiątki historyczne.", arrayOf("Kiry", "Polana Pisana", "Dolina Kościelicka"), thumbnail = "https://i.wpimg.pl/640x480/i1.nocimg.pl/d14/160/18-dolina-koscieliska-najpiekniejsza-dolina.jpg"),
            Trail(11, "Szczeliniec Wielki", "Szczeliniec Wielki jest najwyższym szczytem Gór Stołowych i to od niego warto rozpocząć zwiedzanie tutejszych szlaków. Trasa nie jest ani trudna, ani czasochłonna, za to chwilami pysznie widokowa i pasjonująca.", arrayOf("Karłów", "Szczeliniec Mały", "Szczeliniec Wielki"), thumbnail = "https://www.ahojprzygodo.com/wp-content/uploads/2020/08/szczeliniec-wielki-gory-stolowe-park-narodowy-korona-gor-polski-dolnoslaskie-szczyt-dla-dzieci-70.jpg")

        )

        val hardTrails = arrayOf(
            Trail(0, "Morskie Oko", "Morskie Oko to największe (ok. 35 ha) i jedno z najbardziej znanych jezior tatrzańskich. Położone jest w górnych partiach Doliny Rybiego Potoku stanowiącej część walnej Doliny Białki.", arrayOf("Asfalt", "Morskie Oko"), thumbnail = "https://www.zakopane.pl/assets/zakopane25/media/thumbnails/main_slider/assets/zakopane25/media/files/a573a067-37f3-4ed9-b7e3-36d7360fea3b/dsc-1347w2.jpg"),
            Trail(1, "Rysy", "Masyw Rysów posiada trzy wierzchołki. Na granicy polsko-słowackiej znajduje się średni co do wysokości wierzchołek północno-zachodni, którego różne pomiary dały wysokość od 2498,7 do 2499,6 m (zgodną z tradycyjnie uznawaną wartością 2499m). Wierzchołek ten jest najwyżej położonym punktem Polski.", arrayOf("Morskie Oko", "Czarny Staw", "Rysy"), thumbnail = "https://www.e-horyzont.pl/media/mageplaza/blog/post/r/y/rysy-01.jpg"),
            Trail(2, "Czarny Staw", "Zbliżone kształtem do koła jezioro położone jest na wysokości 1583 m, czyli 188 m wyżej niż lustro Morskiego Oka. Powierzchnia Czarnego Stawu wynosi ok. 20,64 ha, głębokość maksymalna – 76,4 m (drugie miejsce w Tatrach, czwarte w Polsce), pojemność – 7 761 700 m³ wody.", arrayOf("Morskie Oko", "Czarny Staw"), thumbnail = "https://portaltatrzanski.pl/upload/article/e87e4ad9393f74bd78ac74ee2b2c2a19.jpeg"),
            Trail(3, "Orla Perć", "Orla Perć — najtrudniejszy szlak w Tatrach. Marzenie wielu turystów, które wymaga odpowiedniego przygotowania zarówno pod względem kondycji fizycznej, jak i doświadczenia w trudnym górskim terenie. Mocno eksponowany szlak dostarcza wielu emocji i wrażeń. Ciągi sztucznych ubezpieczeń, przepaści, skalne kominki oraz słynna drabinka to elementy, które spotkasz na szlaku.", arrayOf("Scenic Ridge", "Narrow Path"), thumbnail = "https://projektyprzygodowe.pl/wp-content/uploads/2020/09/orla-perc/skrajny-granat-szczelina-1024x768.jpg"),
            Trail(4, "Kozia Przełęcz", "Kozia Przełęcz jest położona na trasie Orlej Perci pomiędzy Zamarłą Turnią i Kozimi Czubami. Jest popularne przede wszystkim ze względu na słynną drabinkę, która schodzą turyści, idący od strony Zawratu. Sama przełęcz to piękne, ale także niebezpieczne miejsce. Jej wcięcie ma zaledwie kilka metrów szerokości, dzięki czemu jest to jedna z najwęższych tatrzańskich przełęczy, dostępnych znakowanym szlakiem.", arrayOf("Waterfall Cascade", "Rocky Path"), thumbnail = "https://tatromaniak.pl/wp-content/uploads/2020/11/65-1.jpg"),
            Trail(5, "Zawrat", "Zawrat należy do najbardziej popularnych przełęczy w polskiej części Tatr. Dostępny jest od Świnicy, Doliny Pięciu Stawów Polskich i Doliny Gąsienicowej. Właśnie droga od schroniska \"Murowaniec\" wydaje się najbardziej ciekawa, a chwilami wręcz tajemnicza, gdyż masyw Zawratu przez większość dnia skutecznie zasłania słońce - szlak zazwyczaj jest w cieniu. Zdecydowanie trudniej wchodzi się tędy niż z Doliny Pięciu Stawów Polskich.", arrayOf("Sunset Peak", "Twilight Ridge"), thumbnail = "https://tatromaniak.pl/wp-content/uploads/2020/07/IMG_3535internet-830x460-c-default.jpg")
        )
    }
}
